/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateApiKeyInput = IDL.Record({ 'name' : IDL.Text });
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ApiKeyPublic = IDL.Record({
  'id' : IDL.Nat,
  'lastUsedAt' : IDL.Opt(Timestamp),
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'keyHash' : IDL.Text,
});
export const CreateApiKeyResult = IDL.Record({
  'key' : ApiKeyPublic,
  'rawKey' : IDL.Text,
});
export const CreateUserInput = IDL.Record({
  'organizationName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'organizationName' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'email' : IDL.Opt(IDL.Text),
});
export const UsageStats = IDL.Record({
  'dailyBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'modelBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalRequests' : IDL.Nat,
});
export const RecordUsageInput = IDL.Record({ 'modelName' : IDL.Text });
export const ContactInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateUserInput = IDL.Record({
  'organizationName' : IDL.Opt(IDL.Text),
  'subscriptionTier' : IDL.Opt(SubscriptionTier),
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createApiKey' : IDL.Func([CreateApiKeyInput], [CreateApiKeyResult], []),
  'createUser' : IDL.Func([CreateUserInput], [UserProfilePublic], []),
  'deleteApiKey' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getUsageStats' : IDL.Func([], [UsageStats], ['query']),
  'getUser' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyPublic)], ['query']),
  'recordUsage' : IDL.Func([RecordUsageInput], [], []),
  'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
  'updateUser' : IDL.Func([UpdateUserInput], [IDL.Opt(UserProfilePublic)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateApiKeyInput = IDL.Record({ 'name' : IDL.Text });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ApiKeyPublic = IDL.Record({
    'id' : IDL.Nat,
    'lastUsedAt' : IDL.Opt(Timestamp),
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'keyHash' : IDL.Text,
  });
  const CreateApiKeyResult = IDL.Record({
    'key' : ApiKeyPublic,
    'rawKey' : IDL.Text,
  });
  const CreateUserInput = IDL.Record({
    'organizationName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'organizationName' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'subscriptionTier' : SubscriptionTier,
    'email' : IDL.Opt(IDL.Text),
  });
  const UsageStats = IDL.Record({
    'dailyBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'modelBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalRequests' : IDL.Nat,
  });
  const RecordUsageInput = IDL.Record({ 'modelName' : IDL.Text });
  const ContactInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateUserInput = IDL.Record({
    'organizationName' : IDL.Opt(IDL.Text),
    'subscriptionTier' : IDL.Opt(SubscriptionTier),
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createApiKey' : IDL.Func([CreateApiKeyInput], [CreateApiKeyResult], []),
    'createUser' : IDL.Func([CreateUserInput], [UserProfilePublic], []),
    'deleteApiKey' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getUsageStats' : IDL.Func([], [UsageStats], ['query']),
    'getUser' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyPublic)], ['query']),
    'recordUsage' : IDL.Func([RecordUsageInput], [], []),
    'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
    'updateUser' : IDL.Func(
        [UpdateUserInput],
        [IDL.Opt(UserProfilePublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };