/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKeyPublic {
  'id' : bigint,
  'lastUsedAt' : [] | [Timestamp],
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'keyHash' : string,
}
export interface ContactInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface CreateApiKeyInput { 'name' : string }
export interface CreateApiKeyResult { 'key' : ApiKeyPublic, 'rawKey' : string }
export interface CreateUserInput {
  'organizationName' : [] | [string],
  'email' : [] | [string],
}
export interface RecordUsageInput { 'modelName' : string }
export type SubscriptionTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'starter' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface UpdateUserInput {
  'organizationName' : [] | [string],
  'subscriptionTier' : [] | [SubscriptionTier],
  'email' : [] | [string],
}
export interface UsageStats {
  'dailyBreakdown' : Array<[string, bigint]>,
  'modelBreakdown' : Array<[string, bigint]>,
  'totalRequests' : bigint,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'organizationName' : [] | [string],
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'email' : [] | [string],
}
export interface _SERVICE {
  'createApiKey' : ActorMethod<[CreateApiKeyInput], CreateApiKeyResult>,
  'createUser' : ActorMethod<[CreateUserInput], UserProfilePublic>,
  'deleteApiKey' : ActorMethod<[bigint], boolean>,
  'getUsageStats' : ActorMethod<[], UsageStats>,
  'getUser' : ActorMethod<[], [] | [UserProfilePublic]>,
  'listApiKeys' : ActorMethod<[], Array<ApiKeyPublic>>,
  'recordUsage' : ActorMethod<[RecordUsageInput], undefined>,
  'submitContact' : ActorMethod<[ContactInput], ContactSubmission>,
  'updateUser' : ActorMethod<[UpdateUserInput], [] | [UserProfilePublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];