/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInput {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface UpdateUserInput {
    organizationName?: string;
    subscriptionTier?: SubscriptionTier;
    email?: string;
}
export interface ContactSubmission {
    id: bigint;
    subject: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
}
export interface RecordUsageInput {
    modelName: string;
}
export interface CreateUserInput {
    organizationName?: string;
    email?: string;
}
export interface CreateApiKeyResult {
    key: ApiKeyPublic;
    rawKey: string;
}
export interface CreateApiKeyInput {
    name: string;
}
export interface ApiKeyPublic {
    id: bigint;
    lastUsedAt?: Timestamp;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    keyHash: string;
}
export interface UsageStats {
    dailyBreakdown: Array<[string, bigint]>;
    modelBreakdown: Array<[string, bigint]>;
    totalRequests: bigint;
}
export interface UserProfilePublic {
    id: UserId;
    organizationName?: string;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    email?: string;
}
export enum SubscriptionTier {
    pro = "pro",
    enterprise = "enterprise",
    starter = "starter",
    free = "free"
}
export interface backendInterface {
    createApiKey(input: CreateApiKeyInput): Promise<CreateApiKeyResult>;
    createUser(input: CreateUserInput): Promise<UserProfilePublic>;
    deleteApiKey(keyId: bigint): Promise<boolean>;
    getUsageStats(): Promise<UsageStats>;
    getUser(): Promise<UserProfilePublic | null>;
    listApiKeys(): Promise<Array<ApiKeyPublic>>;
    recordUsage(input: RecordUsageInput): Promise<void>;
    submitContact(input: ContactInput): Promise<ContactSubmission>;
    updateUser(input: UpdateUserInput): Promise<UserProfilePublic | null>;
}
import type { ApiKeyPublic as _ApiKeyPublic, CreateApiKeyResult as _CreateApiKeyResult, CreateUserInput as _CreateUserInput, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UpdateUserInput as _UpdateUserInput, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createApiKey(arg0: CreateApiKeyInput): Promise<CreateApiKeyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createApiKey(arg0);
                return from_candid_CreateApiKeyResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApiKey(arg0);
            return from_candid_CreateApiKeyResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: CreateUserInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(to_candid_CreateUserInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(to_candid_CreateUserInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteApiKey(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApiKey(arg0);
            return result;
        }
    }
    async getUsageStats(): Promise<UsageStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageStats();
            return result;
        }
    }
    async getUser(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApiKeys(): Promise<Array<ApiKeyPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApiKeys();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApiKeys();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordUsage(arg0: RecordUsageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordUsage(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactInput): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateUser(arg0: UpdateUserInput): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_UpdateUserInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_UpdateUserInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApiKeyPublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKeyPublic): ApiKeyPublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CreateApiKeyResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateApiKeyResult): CreateApiKeyResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    key: _ApiKeyPublic;
    rawKey: string;
}): {
    key: ApiKeyPublic;
    rawKey: string;
} {
    return {
        key: from_candid_ApiKeyPublic_n3(_uploadFile, _downloadFile, value.key),
        rawKey: value.rawKey
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lastUsedAt: [] | [_Timestamp];
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    isActive: boolean;
    keyHash: string;
}): {
    id: bigint;
    lastUsedAt?: Timestamp;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    keyHash: string;
} {
    return {
        id: value.id,
        lastUsedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.lastUsedAt)),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        keyHash: value.keyHash
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    organizationName: [] | [string];
    createdAt: _Timestamp;
    subscriptionTier: _SubscriptionTier;
    email: [] | [string];
}): {
    id: UserId;
    organizationName?: string;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    email?: string;
} {
    return {
        id: value.id,
        organizationName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.organizationName)),
        createdAt: value.createdAt,
        subscriptionTier: from_candid_SubscriptionTier_n11(_uploadFile, _downloadFile, value.subscriptionTier),
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
} | {
    free: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "enterprise" in value ? SubscriptionTier.enterprise : "starter" in value ? SubscriptionTier.starter : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiKeyPublic>): Array<ApiKeyPublic> {
    return value.map((x)=>from_candid_ApiKeyPublic_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CreateUserInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateUserInput): _CreateUserInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserInput): _UpdateUserInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationName?: string;
    subscriptionTier?: SubscriptionTier;
    email?: string;
}): {
    organizationName: [] | [string];
    subscriptionTier: [] | [_SubscriptionTier];
    email: [] | [string];
} {
    return {
        organizationName: value.organizationName ? candid_some(value.organizationName) : candid_none(),
        subscriptionTier: value.subscriptionTier ? candid_some(to_candid_SubscriptionTier_n17(_uploadFile, _downloadFile, value.subscriptionTier)) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationName?: string;
    email?: string;
}): {
    organizationName: [] | [string];
    email: [] | [string];
} {
    return {
        organizationName: value.organizationName ? candid_some(value.organizationName) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.enterprise ? {
        enterprise: null
    } : value == SubscriptionTier.starter ? {
        starter: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
